package com.umbrella.scada.controller;

public enum ActionKey {
	START,
	STOP, 
	UPDATE_STATE,
	UPDATE_CAKE_CONVEYOR_BELT_ATTR,
	UPDATE_BLISTER_CONVEYOR_BELT_ATTR,
	UPDATE_PACKAGE_CONVEYOR_BELT_ATTR,
	UPDATE_ROBOT1_ATTR,
	UPDATE_ROBOT2_ATTR;
}
