package com.umbrella.scada.controller;

public enum ActionKey {
	START,
	STOP, 
	UPDATE_STATE,
	UPDATE_CAKE_CONVEYOR_BELT,
	UPDATE_BLISTER_CONVEYOR_BELT,
	UPDATE_PACKAGE_CONVEYOR_BELT,
	UPDATE_ROBOT1,
	UPDATE_ROBOT2, 
	UPDATE_CAKE_DEPOT, AU1_CAKES_POS, UPDATE_ROBOT_CONTENT;
}
