package com.umbrella.scada.controller;

public enum ActionKey {
	START,
	STOP, 
	EMERGENCY_STOP,
	FAIL_STOP,
	UPDATE_STATE,
	UPDATE_CAKE_CONVEYOR_BELT,
	UPDATE_BLISTER_CONVEYOR_BELT,
	UPDATE_PACKAGE_CONVEYOR_BELT,
	UPDATE_ROBOT1,
	UPDATE_ROBOT2, 
	UPDATE_CAKE_DEPOT,
	UPDATE_CHOCOLAT_DEPOT,
	UPDATE_CARAMEL_DEPOT,
	AU1_CAKES_POS, 
	AU2_BLISTER_POS,
	AU3_PACKAGE_POS,
	TABLE_CONTENT,
	UPDATE_ROBOT_CONTENT, 
	SEND_CONFIGURATION, 
	UPDATE_CONFIGURATION,
	CONVEYOR_BELT_MOVE,
	NUMBER_PACKAGES;
}
