package com.umbrella.scada.view.localization;

public enum LocalizatorIDs {
	MENUBAR_FILE, MENUBAR_OPTIONS, MENUBAR_LANGUAGE, MENUBAR_ES_LANGUAGE, MENUBAR_EN_LANGUAGE, BUTTON_INIT, BUTTON_PAUSE, BUTTON_STOP
}
