package com.umbrella.scada.view.localization;

public enum LocalizatorIDs {
	MENUBAR_SCADA,
	MENUBAR_REPORTS,
	MENUBAR_EXIT,
	MENUBAR_OPTIONS,
	MENUBAR_LANGUAGE,
	MENUBAR_ES_LANGUAGE,
	MENUBAR_EN_LANGUAGE,
	BUTTON_INIT,
	BUTTON_PAUSE,
	BUTTON_STOP,
	CONVEYOR_BELT,
	VOID_CONVEYOR_BELT,
	CAKE_CONVEYOR_BELT,
	BLISTER_CONVEYOR_BELT,
	PACKAGE_CONVEYOR_BELT,
	ROBOT_1_TITLE,
	ROBOT_2_TITLE,
	SPEED,
	M_MIN
}
